#!/bin/bash

set -e

cd "$(dirname "$0")"

TOKEN_TYPES_H=token-types.h

# --------------------------------------------------------- Create TOKEN_TYPES_C
cat <<EOF

// AUTOGENERATED by $(basename "$0")

#include "scanner/token-types.h"

const char* token_id_to_str(uint16_t token_id)
{
   switch(token_id) {
EOF

cat "$TOKEN_TYPES_H" | grep -E "^#define [A-Z_0-9]+ +[0-9]+ *$" | sed 's/^#define \([A-Z_0-9]*\) *\([0-9]*\).*$/   case \2: return "\1";/' | sort -k2 -n 

cat <<EOF
   }
   return "?";
}

EOF



